version: "3.4"

services:
  java:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      target: dev
    volumes:
       - ./:/code
    working_dir: /code
    command: ["mvn", "tomcat7:run"]
    ports: 
      - "8999:8999"
    tty: true
