version: "3.4"

services:
  java:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile
      target: dev
    volumes:
       - ./:/code
    working_dir: /code
    command: ["mvn tomcat7:run"]
    environment:
      SERVER_PORT: ${SERVER_PORT}
      LOG_APPLICATION_NAME: ${LOG_APPLICATION_NAME}
    ports: 
      - "${SERVER_PORT}:${SERVER_PORT}"
    tty: true
